FROM golang:1.19-alpine as builder
RUN mkdir /build 
WORKDIR /build 
COPY go.mod .
COPY go.sum .
RUN go mod download && go mod verify
COPY ./cmd/ .
RUN go build -o app .
EXPOSE 8080
CMD ["/build/app"]